#pragma warning disable 0618
#pragma warning disable 1574
using System;
using System.CodeDom.Compiler;

namespace Mtconnect.DataTypes
{
	/// <summary>
	/// View in the MTConnect Model browser <seealso href="https://model.mtconnect.org/#Enumeration___19_0_3_45f01b9_1580398370126_672808_12777">model.mtconnect.org</seealso>
	/// </summary>
	/// <remarks>
	/// <list type="bullet">
	/// <item><b>Introduced</b>: <see href="https://model.mtconnect.org/#_Version_">v</see></item>
	/// <item><b>Deprecated</b>: <see href="https://model.mtconnect.org/#_Version_">v</see></item>
	/// </list>
	/// </remarks>
	[Obsolete("Deprecated in v according to https://model.mtconnect.org/#_Version_")]
	[GeneratedCode("MtconnectTranspiler.Sinks.CSharp", "1.0.15.3")]
	public enum SampleEnum
	{
		/// <summary>
		/// positive rate of change of velocity.
		/// </summary>
		ACCELERATION,
		/// <summary>
		/// accumulated time for an activity or event.
		/// </summary>
		ACCUMULATED_TIME,
		/// <summary>
		/// strength of electrical current.  <b>DEPRECATED</b> in <i>Version 1.6</i>s. Replaced by <c>AMPERAGE_AC</c> and <c>AMPERAGE_DC</c>.
		/// </summary>
		AMPERAGE,
		/// <summary>
		/// angular position.
		/// </summary>
		ANGLE,
		/// <summary>
		/// positive rate of change of angular velocity.
		/// </summary>
		ANGULAR_ACCELERATION,
		/// <summary>
		/// rate of change of angular position.
		/// </summary>
		ANGULAR_VELOCITY,
		/// <summary>
		/// feedrate of a linear axis.
		/// </summary>
		AXIS_FEEDRATE,
		/// <summary>
		/// fluid capacity of an object or container.
		/// </summary>
		CAPACITY_FLUID,
		/// <summary>
		/// geometric capacity of an object or container.
		/// </summary>
		CAPACITY_SPATIAL,
		/// <summary>
		/// percentage of one component within a mixture of components.
		/// </summary>
		CONCENTRATION,
		/// <summary>
		/// ability of a material to conduct electricity.
		/// </summary>
		CONDUCTIVITY,
		/// <summary>
		/// speed difference (relative velocity) between the cutting mechanism and the surface of the workpiece it is operating on.
		/// </summary>
		CUTTING_SPEED,
		/// <summary>
		/// volumetric mass of a material per unit volume of that material.
		/// </summary>
		DENSITY,
		/// <summary>
		/// rate of change in spatial volume of material deposited in an additive manufacturing process.
		/// </summary>
		DEPOSITION_ACCELERATION_VOLUMETRIC,
		/// <summary>
		/// density of the material deposited in an additive manufacturing process per unit of volume.
		/// </summary>
		DEPOSITION_DENSITY,
		/// <summary>
		/// mass of the material deposited in an additive manufacturing process.
		/// </summary>
		DEPOSITION_MASS,
		/// <summary>
		/// rate at which a spatial volume of material is deposited in an additive manufacturing process.
		/// </summary>
		DEPOSITION_RATE_VOLUMETRIC,
		/// <summary>
		/// spatial volume of material to be deposited in an additive manufacturing process.
		/// </summary>
		DEPOSITION_VOLUME,
		/// <summary>
		/// change in position of an object.
		/// </summary>
		DISPLACEMENT,
		/// <summary>
		/// <see cref="Wattage">Wattage</see> used or generated by a component over an interval of time.
		/// </summary>
		ELECTRICAL_ENERGY,
		/// <summary>
		/// amount of time a piece of equipment or a sub-part of a piece of equipment has performed specific activities.
		/// </summary>
		EQUIPMENT_TIMER,
		/// <summary>
		/// amount of a substance remaining compared to the planned maximum amount of that substance.
		/// </summary>
		FILL_LEVEL,
		/// <summary>
		/// rate of flow of a fluid.
		/// </summary>
		FLOW,
		/// <summary>
		/// number of occurrences of a repeating event per unit time.
		/// </summary>
		FREQUENCY,
		/// <summary>
		/// position in three-dimensional space.  <b>DEPRECATED</b> in Version 1.1.
		/// </summary>
		GLOBAL_POSITION,
		/// <summary>
		/// length of an object.
		/// </summary>
		LENGTH,
		/// <summary>
		/// level of a resource.  <b>DEPRECATED</b> in <i>Version 1.2</i>s.  See <c>FILL_LEVEL</c>.
		/// </summary>
		LEVEL,
		/// <summary>
		/// <i>force</i> applied to a mass in one direction only.
		/// </summary>
		LINEAR_FORCE,
		/// <summary>
		/// actual versus the standard rating of a piece of equipment.
		/// </summary>
		LOAD,
		/// <summary>
		/// mass of an object(s) or an amount of material.
		/// </summary>
		MASS,
		/// <summary>
		/// feedrate for the axes, or a single axis, associated with a <see cref="Path">Path</see> component.
		/// </summary>
		PATH_FEEDRATE,
		/// <summary>
		/// feedrate for the axes, or a single axis.
		/// </summary>
		PATH_FEEDRATE_PER_REVOLUTION,
		/// <summary>
		/// position of a control point associated with a <see cref="Controller">Controller</see> or a <see cref="Path">Path</see>.
		/// </summary>
		PATH_POSITION,
		/// <summary>
		/// acidity or alkalinity of a solution.
		/// </summary>
		PH,
		/// <summary>
		/// point along an axis in a <i>cartesian coordinate system</i>.
		/// </summary>
		POSITION,
		/// <summary>
		/// ratio of real power flowing to a load to the apparent power in that AC circuit.
		/// </summary>
		POWER_FACTOR,
		/// <summary>
		/// force per unit area measured relative to atmospheric pressure.   Commonly referred to as gauge pressure.
		/// </summary>
		PRESSURE,
		/// <summary>
		/// amount of time a piece of equipment has performed different types of activities associated with the process being performed at that piece of equipment.
		/// </summary>
		PROCESS_TIMER,
		/// <summary>
		/// degree to which a substance opposes the passage of an electric current.
		/// </summary>
		RESISTANCE,
		/// <summary>
		/// rotational speed of a rotary axis.
		/// </summary>
		ROTARY_VELOCITY,
		/// <summary>
		/// sound level or sound pressure level relative to atmospheric pressure.
		/// </summary>
		SOUND_LEVEL,
		/// <summary>
		/// rotational speed of the rotary axis.  <b>DEPRECATED</b> in <i>Version 1.2</i>s.  Replaced by <c>ROTARY_VELOCITY</c>.
		/// </summary>
		SPINDLE_SPEED,
		/// <summary>
		/// amount of deformation per unit length of an object when a load is applied.
		/// </summary>
		STRAIN,
		/// <summary>
		/// degree of hotness or coldness measured on a definite scale.
		/// </summary>
		TEMPERATURE,
		/// <summary>
		/// force that stretches or elongates an object.
		/// </summary>
		TENSION,
		/// <summary>
		/// angular displacement.
		/// </summary>
		TILT,
		/// <summary>
		/// turning force exerted on an object or by an object.
		/// </summary>
		TORQUE,
		/// <summary>
		/// rate of change of position of a <see cref="Component">Component</see>.
		/// </summary>
		VELOCITY,
		/// <summary>
		/// fluid's resistance to flow.
		/// </summary>
		VISCOSITY,
		/// <summary>
		/// electrical potential between two points.  <b>DEPRECATED</b> in <i>Version 1.6</i>s. Replaced by <c>VOLTAGE_AC</c> and <c>VOLTAGE_DC</c>.
		/// </summary>
		VOLTAGE,
		/// <summary>
		/// apparent power in an electrical circuit, equal to the product of root-mean-square (RMS) voltage and RMS current (commonly referred to as VA).
		/// </summary>
		VOLT_AMPERE,
		/// <summary>
		/// reactive power in an AC electrical circuit (commonly referred to as VAR).
		/// </summary>
		VOLT_AMPERE_REACTIVE,
		/// <summary>
		/// fluid volume of an object or container.
		/// </summary>
		VOLUME_FLUID,
		/// <summary>
		/// geometric volume of an object or container.
		/// </summary>
		VOLUME_SPATIAL,
		/// <summary>
		/// power flowing through or dissipated by an electrical circuit or piece of equipment.
		/// </summary>
		WATTAGE,
		/// <summary>
		/// electrical current that reverses direction at regular short intervals.
		/// </summary>
		AMPERAGE_AC,
		/// <summary>
		/// electric current flowing in one direction only.
		/// </summary>
		AMPERAGE_DC,
		/// <summary>
		/// electrical potential between two points in an electrical circuit in which the current periodically reverses direction.
		/// </summary>
		VOLTAGE_AC,
		/// <summary>
		/// electrical potential between two points in an electrical circuit in which the current is unidirectional.
		/// </summary>
		VOLTAGE_DC,
		/// <summary>
		/// dimension of an entity relative to the X direction of the referenced coordinate system. 
		/// </summary>
		X_DIMENSION,
		/// <summary>
		/// dimension of an entity relative to the Y direction of the referenced coordinate system.
		/// </summary>
		Y_DIMENSION,
		/// <summary>
		/// dimension of an entity relative to the Z direction of the referenced coordinate system.
		/// </summary>
		Z_DIMENSION,
		/// <summary>
		/// dimension of a diameter.
		/// </summary>
		DIAMETER,
		/// <summary>
		/// angular position of a plane or vector relative to a <i>cartesian coordinate system</i>
		/// </summary>
		ORIENTATION,
		/// <summary>
		/// amount of water vapor present expressed as a percent to reach saturation at the same temperature.
		/// </summary>
		HUMIDITY_RELATIVE,
		/// <summary>
		/// amount of water vapor expressed in grams per cubic meter.
		/// </summary>
		HUMIDITY_ABSOLUTE,
		/// <summary>
		/// ratio of the water vapor present over the total weight of the water vapor and air present expressed as a percent.
		/// </summary>
		HUMIDITY_SPECIFIC,
		/// <summary>
		/// average rate of change of values for data items in the MTConnect streams. The average is computed over a rolling window defined by the implementation.
		/// </summary>
		OBSERVATION_UPDATE_RATE,
		/// <summary>
		/// average rate of change of values for assets in the MTConnect streams.   The average is computed over a rolling window defined by the implementation.
		/// </summary>
		ASSET_UPDATE_RATE,
		/// <summary>
		/// change of pressure per unit time.
		/// </summary>
		PRESSURIZATION_RATE,
		/// <summary>
		/// negative rate of change of velocity.
		/// </summary>
		DECELERATION,
		/// <summary>
		/// negative rate of change of angular velocity.
		/// </summary>
		ANGULAR_DECELERATION,
		/// <summary>
		/// force per unit area measured relative to a vacuum.
		/// </summary>
		PRESSURE_ABSOLUTE,
		/// <summary>
		/// percentage open where 100% is fully open and 0% is fully closed.
		/// </summary>
		OPENNESS,
		/// <summary>
		/// temperature at which moisture begins to condense, corresponding to saturation for a given absolute humidity.
		/// </summary>
		DEW_POINT,
		/// <summary>
		/// force relative to earth's gravity.
		/// </summary>
		GRAVITATIONAL_FORCE,
		/// <summary>
		/// acceleration relative to Earth's gravity of 9.80665 <c>METER/SECOND^2</c>.
		/// </summary>
		GRAVITATIONAL_ACCELERATION,
		/// <summary>
		/// maximum rated charge a battery is capable of maintaining based on the battery discharging at a specified current over a specified time period.
		/// </summary>
		BATTERY_CAPACITY,
		/// <summary>
		/// value of current being drawn from the <see cref="Component">Component</see>.
		/// </summary>
		DISCHARGE_RATE,
		/// <summary>
		/// value of the current being supplied to the <see cref="Component">Component</see> for the purpose of charging.
		/// </summary>
		CHARGE_RATE,
		/// <summary>
		/// value of the battery's present capacity expressed as a percentage of the battery's maximum rated capacity.
		/// </summary>
		BATTERY_CHARGE,
		/// <summary>
		/// difference between actual and commanded position at the end of a motion.
		/// </summary>
		SETTLING_ERROR,
		/// <summary>
		/// difference between actual and commanded position at any specific point in time during a motion.
		/// </summary>
		FOLLOWING_ERROR,
		/// <summary>
		/// difference between the commanded encoder/resolver position, and the actual encoder/resolver position when motion is complete.
		/// </summary>
		SETTLING_ERROR_LINEAR,
		/// <summary>
		/// angular difference between the commanded encoder/resolver position, and the actual encoder/resolver position when motion is complete.
		/// </summary>
		SETTLING_ERROR_ANGULAR,
		/// <summary>
		/// difference between the commanded encoder/resolver position and the actual encoder/resolver position at any specified point in time during a motion.
		/// </summary>
		FOLLOWING_ERROR_LINEAR,
		/// <summary>
		/// angular difference between the commanded encoder/resolver position and the actual encoder/resolver position at any specified point in time during a motion.
		/// </summary>
		FOLLOWING_ERROR_ANGULAR,
		/// <summary>
		/// absolute value of the change in position along a vector.
		/// </summary>
		DISPLACEMENT_LINEAR,
		/// <summary>
		/// absolute value of the change in angular position around a vector
		/// </summary>
		DISPLACEMENT_ANGULAR,
		/// <summary>
		/// point in a <i>cartesian coordinate system</i>.
		/// </summary>
		POSITION_CARTESIAN,
	}
}